SET NOCOUNT ON;

SELECT
    CAST(wo.STATUS AS NVARCHAR(100)) AS WORK_ORDER_STATUS,
    CAST(op.STATUS AS NVARCHAR(100)) AS OPERATION_STATUS,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT wo.BASE_ID) AS DISTINCT_WORK_ORDERS,
    COUNT(DISTINCT CONCAT(op.WORKORDER_BASE_ID, '|', CAST(op.SEQUENCE_NO AS NVARCHAR(50)))) AS DISTINCT_SEQUENCES,
    COUNT(DISTINCT op.RESOURCE_ID) AS DISTINCT_RESOURCES
FROM dbo.OPERATION AS op
INNER JOIN dbo.WORK_ORDER AS wo
    ON wo.BASE_ID = op.WORKORDER_BASE_ID
   AND wo.TYPE = op.WORKORDER_TYPE
WHERE op.WORKORDER_TYPE = 'W'
  AND wo.TYPE = 'W'
GROUP BY wo.STATUS, op.STATUS
ORDER BY WORK_ORDER_STATUS, OPERATION_STATUS;