SET NOCOUNT ON;

WITH RankedStatusSamples AS (
    SELECT
        CAST(wo.STATUS AS NVARCHAR(100)) AS WORK_ORDER_STATUS,
        CAST(op.STATUS AS NVARCHAR(100)) AS OPERATION_STATUS,
        wo.BASE_ID AS WORK_ORDER_ID,
        wo.PART_ID,
        wo.DESIRED_QTY,
        wo.STATUS_EFF_DATE AS WORK_ORDER_STATUS_EFF_DATE,
        op.SEQUENCE_NO,
        op.RESOURCE_ID,
        sr.DESCRIPTION AS RESOURCE_DESCRIPTION,
        CAST(sr.TYPE AS NVARCHAR(100)) AS RESOURCE_TYPE,
        sr.DEPARTMENT_ID,
        sr.SCHEDULE_GROUP_ID,
        op.SETUP_COMPLETED,
        op.COMPLETED_QTY,
        op.CALC_END_QTY,
        op.SCHED_START_DATE,
        op.SCHED_FINISH_DATE,
        op.STATUS_EFF_DATE AS OPERATION_STATUS_EFF_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY wo.STATUS, op.STATUS
            ORDER BY
                COALESCE(op.STATUS_EFF_DATE, wo.STATUS_EFF_DATE) DESC,
                wo.BASE_ID,
                op.SEQUENCE_NO
        ) AS STATUS_PAIR_ROW_NUM
    FROM dbo.OPERATION AS op
    INNER JOIN dbo.WORK_ORDER AS wo
        ON wo.BASE_ID = op.WORKORDER_BASE_ID
       AND wo.TYPE = op.WORKORDER_TYPE
    LEFT JOIN dbo.SHOP_RESOURCE AS sr
        ON sr.ID = op.RESOURCE_ID
    WHERE op.WORKORDER_TYPE = 'W'
      AND wo.TYPE = 'W'
)
SELECT
    WORK_ORDER_STATUS,
    OPERATION_STATUS,
    WORK_ORDER_ID,
    PART_ID,
    DESIRED_QTY,
    WORK_ORDER_STATUS_EFF_DATE,
    SEQUENCE_NO,
    RESOURCE_ID,
    RESOURCE_DESCRIPTION,
    RESOURCE_TYPE,
    DEPARTMENT_ID,
    SCHEDULE_GROUP_ID,
    SETUP_COMPLETED,
    COMPLETED_QTY,
    CALC_END_QTY,
    SCHED_START_DATE,
    SCHED_FINISH_DATE,
    OPERATION_STATUS_EFF_DATE,
    STATUS_PAIR_ROW_NUM
FROM RankedStatusSamples
WHERE STATUS_PAIR_ROW_NUM <= 100
ORDER BY WORK_ORDER_STATUS, OPERATION_STATUS, STATUS_PAIR_ROW_NUM;