SET NOCOUNT ON;

SELECT
    CASE
        WHEN ps.SITE_ID IS NULL OR LTRIM(RTRIM(ps.SITE_ID)) = '' THEN 'NO_PART_SITE_ROW'
        ELSE ps.SITE_ID
    END AS SITE_BUCKET,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT r.PART_ID) AS DISTINCT_WORK_ORDER_PARTS,
    COUNT(DISTINCT r.WORKORDER_BASE_ID) AS DISTINCT_WORK_ORDERS
FROM dbo.REQUIREMENT AS r
LEFT JOIN dbo.PART_SITE AS ps
    ON ps.PART_ID = r.PART_ID
   AND ps.SITE_ID = 'MTM2'
WHERE r.WORKORDER_TYPE = 'W'
GROUP BY
    CASE
        WHEN ps.SITE_ID IS NULL OR LTRIM(RTRIM(ps.SITE_ID)) = '' THEN 'NO_PART_SITE_ROW'
        ELSE ps.SITE_ID
    END
ORDER BY SITE_BUCKET;