SET NOCOUNT ON;

SELECT 'CUSTOMER_ORDER' AS TABLE_NAME, 'CREATE_DATE' AS COLUMN_NAME,
       COUNT(*) AS TOTAL_ROWS,
       SUM(CASE WHEN CREATE_DATE IS NULL THEN 0 ELSE 1 END) AS POPULATED_ROWS,
       MIN(CREATE_DATE) AS MIN_VALUE,
       MAX(CREATE_DATE) AS MAX_VALUE
FROM dbo.CUSTOMER_ORDER

UNION ALL

SELECT 'CUSTOMER_ORDER', 'ORDER_DATE', COUNT(*),
       SUM(CASE WHEN ORDER_DATE IS NULL THEN 0 ELSE 1 END),
       MIN(ORDER_DATE), MAX(ORDER_DATE)
FROM dbo.CUSTOMER_ORDER

UNION ALL

SELECT 'CUST_ORDER_LINE', 'DESIRED_SHIP_DATE', COUNT(*),
       SUM(CASE WHEN DESIRED_SHIP_DATE IS NULL THEN 0 ELSE 1 END),
       MIN(DESIRED_SHIP_DATE), MAX(DESIRED_SHIP_DATE)
FROM dbo.CUST_ORDER_LINE

UNION ALL

SELECT 'CUST_ORDER_LINE', 'PROMISE_DATE', COUNT(*),
       SUM(CASE WHEN PROMISE_DATE IS NULL THEN 0 ELSE 1 END),
       MIN(PROMISE_DATE), MAX(PROMISE_DATE)
FROM dbo.CUST_ORDER_LINE

UNION ALL

SELECT 'CUST_ORDER_LINE', 'STATUS_EFF_DATE', COUNT(*),
       SUM(CASE WHEN STATUS_EFF_DATE IS NULL THEN 0 ELSE 1 END),
       MIN(STATUS_EFF_DATE), MAX(STATUS_EFF_DATE)
FROM dbo.CUST_ORDER_LINE

UNION ALL

SELECT 'CUST_ORDER_ALLOC', 'WANT_DATE', COUNT(*),
       SUM(CASE WHEN WANT_DATE IS NULL THEN 0 ELSE 1 END),
       MIN(WANT_DATE), MAX(WANT_DATE)
FROM dbo.CUST_ORDER_ALLOC

UNION ALL

SELECT 'CUST_ORDER_ALLOC', 'FINISH_DATE', COUNT(*),
       SUM(CASE WHEN FINISH_DATE IS NULL THEN 0 ELSE 1 END),
       MIN(FINISH_DATE), MAX(FINISH_DATE)
FROM dbo.CUST_ORDER_ALLOC

UNION ALL

SELECT 'WORK_ORDER', 'CREATE_DATE', COUNT(*),
       SUM(CASE WHEN CREATE_DATE IS NULL THEN 0 ELSE 1 END),
       MIN(CREATE_DATE), MAX(CREATE_DATE)
FROM dbo.WORK_ORDER

ORDER BY TABLE_NAME, COLUMN_NAME;