SET NOCOUNT ON;

SELECT
    DEMAND_TYPE,
    SUPPLY_TYPE,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT ORDER_ID) AS DISTINCT_ORDER_IDS,
    COUNT(DISTINCT CONCAT(ORDER_ID, '|', ORDER_LINE_NO, '|', ORDER_DEL_NO)) AS DISTINCT_ORDER_LINES,
    COUNT(DISTINCT CONCAT(BASE_ID, '|', LOT_ID, '|', SPLIT_ID)) AS DISTINCT_SUPPLY_KEYS,
    MIN(WANT_DATE) AS MIN_WANT_DATE,
    MAX(WANT_DATE) AS MAX_WANT_DATE,
    MIN(FINISH_DATE) AS MIN_FINISH_DATE,
    MAX(FINISH_DATE) AS MAX_FINISH_DATE
FROM dbo.CUST_ORDER_ALLOC
GROUP BY DEMAND_TYPE, SUPPLY_TYPE
ORDER BY DEMAND_TYPE, SUPPLY_TYPE;