SET NOCOUNT ON;

SELECT DISTINCT TOP (1000)
    SITE_ID,
    CUST_ID,
    ORDER_ID,
    ORDER_LINE_NO,
    ORDER_DEL_NO,
    DEMAND_KEY,
    DEMAND_TYPE,
    SUPPLY_KEY,
    SUPPLY_TYPE,
    BASE_ID,
    LOT_ID,
    SPLIT_ID,
    PART_ID,
    WANT_DATE,
    FINISH_DATE,
    ORDER_QTY,
    SHIPPED_QTY,
    DESIRED_QTY,
    RECEIVED_QTY,
    ALLOCATED_QTY
FROM dbo.CUST_ORDER_ALLOC
WHERE CUST_ID IS NOT NULL
  AND LTRIM(RTRIM(CUST_ID)) <> ''
ORDER BY WANT_DATE DESC, ORDER_ID, ORDER_LINE_NO;