SET NOCOUNT ON;

SELECT
    sr.ID AS RESOURCE_ID,
    sr.DESCRIPTION AS RESOURCE_DESCRIPTION,
    CAST(sr.TYPE AS NVARCHAR(100)) AS RESOURCE_TYPE,
    sr.DEPARTMENT_ID,
    sr.SCHEDULE_GROUP_ID,
    CAST(sr.SCHEDULE_NORMALLY AS NVARCHAR(100)) AS SCHEDULE_NORMALLY,
    COUNT(op.RESOURCE_ID) AS OPERATION_ROW_COUNT,
    COUNT(DISTINCT op.WORKORDER_BASE_ID) AS DISTINCT_WORK_ORDERS,
    COUNT(DISTINCT CONCAT(op.WORKORDER_BASE_ID, '|', CAST(op.SEQUENCE_NO AS NVARCHAR(50)))) AS DISTINCT_SEQUENCES,
    MIN(op.SCHED_START_DATE) AS FIRST_SCHED_START_DATE,
    MAX(op.SCHED_FINISH_DATE) AS LAST_SCHED_FINISH_DATE
FROM dbo.SHOP_RESOURCE AS sr
LEFT JOIN dbo.OPERATION AS op
    ON op.RESOURCE_ID = sr.ID
   AND op.WORKORDER_TYPE = 'W'
GROUP BY
    sr.ID,
    sr.DESCRIPTION,
    sr.TYPE,
    sr.DEPARTMENT_ID,
    sr.SCHEDULE_GROUP_ID,
    sr.SCHEDULE_NORMALLY
ORDER BY sr.ID;