SET NOCOUNT ON;

SELECT 'CUST_ORDER_LINE' AS TABLE_NAME, 'LINE_STATUS' AS COLUMN_NAME,
       CAST(LINE_STATUS AS NVARCHAR(100)) AS COLUMN_VALUE,
       COUNT(*) AS ROW_COUNT
FROM dbo.CUST_ORDER_LINE
GROUP BY LINE_STATUS

UNION ALL

SELECT 'CUST_ORDER_LINE', 'SHIP_ORDER_STATUS',
       CAST(SHIP_ORDER_STATUS AS NVARCHAR(100)),
       COUNT(*)
FROM dbo.CUST_ORDER_LINE
GROUP BY SHIP_ORDER_STATUS

UNION ALL

SELECT 'CO_PRODUCT', 'LINE_STATUS',
       CAST(LINE_STATUS AS NVARCHAR(100)),
       COUNT(*)
FROM dbo.CO_PRODUCT
GROUP BY LINE_STATUS

UNION ALL

SELECT 'WORK_ORDER', 'STATUS',
       CAST(STATUS AS NVARCHAR(100)),
       COUNT(*)
FROM dbo.WORK_ORDER
GROUP BY STATUS

ORDER BY TABLE_NAME, COLUMN_NAME, COLUMN_VALUE;