SET NOCOUNT ON;

SELECT DISTINCT
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME IN (
    'CUST_ORDER_ID',
    'LINE_NO',
    'ORDER_ID',
    'ORDER_LINE_NO',
    'ORDER_DEL_NO',
    'WBS_CUST_ORDER_ID',
    'WORKORDER_TYPE',
    'WORKORDER_BASE_ID',
    'WORKORDER_LOT_ID',
    'WORKORDER_SPLIT_ID',
    'WORKORDER_SUB_ID',
    'TYPE',
    'BASE_ID',
    'LOT_ID',
    'SPLIT_ID',
    'SUB_ID',
    'LINE_STATUS',
    'SHIP_ORDER_STATUS',
    'STATUS',
    'CREATE_DATE',
    'ORDER_DATE',
    'DESIRED_SHIP_DATE',
    'PROMISE_DATE',
    'STATUS_EFF_DATE',
    'WANT_DATE',
    'FINISH_DATE',
    'ALLOCATED_QTY',
    'FULFILLED_QTY',
    'TOTAL_SHIPPED_QTY',
    'RECEIVED_QTY'
)
ORDER BY COLUMN_NAME, TABLE_SCHEMA, TABLE_NAME;