SET NOCOUNT ON;

SELECT TOP (1000)
    coa.ORDER_ID AS CUSTOMER_ORDER_ID,
    coa.ORDER_LINE_NO,
    coa.ORDER_DEL_NO,
    coa.DEMAND_TYPE,
    coa.SUPPLY_TYPE,
    coa.SUPPLY_KEY,
    coa.BASE_ID AS WORKORDER_BASE_ID,
    coa.LOT_ID AS WORKORDER_LOT_ID,
    coa.SPLIT_ID AS WORKORDER_SPLIT_ID,
    wo.SUB_ID AS WORKORDER_SUB_ID,
    wo.TYPE AS WORKORDER_TYPE,
    wo.PART_ID AS WORKORDER_PART_ID,
    coa.PART_ID AS DEMAND_PART_ID,
    coa.ALLOCATED_QTY,
    coa.WANT_DATE,
    coa.FINISH_DATE
FROM dbo.CUST_ORDER_ALLOC AS coa
LEFT JOIN dbo.WORK_ORDER AS wo
    ON wo.TYPE = 'W'
   AND wo.BASE_ID = coa.BASE_ID
   AND wo.LOT_ID = coa.LOT_ID
   AND wo.SPLIT_ID = coa.SPLIT_ID
WHERE coa.DEMAND_TYPE IN ('CD', 'CO')
  AND coa.SUPPLY_TYPE = 'WO'
  AND coa.ORDER_ID IS NOT NULL
  AND LTRIM(RTRIM(coa.ORDER_ID)) <> ''
ORDER BY coa.WANT_DATE DESC, coa.ORDER_ID, coa.ORDER_LINE_NO, coa.ORDER_DEL_NO;