SET NOCOUNT ON;

SELECT 'CUST_ORDER_ALLOC' AS TABLE_NAME, 'ORDER_ID' AS COLUMN_NAME,
       COUNT(*) AS TOTAL_ROWS,
       SUM(CASE WHEN ORDER_ID IS NULL OR LTRIM(RTRIM(ORDER_ID)) = '' THEN 0 ELSE 1 END) AS POPULATED_ROWS
FROM dbo.CUST_ORDER_ALLOC

UNION ALL

SELECT 'CUST_ORDER_ALLOC', 'ORDER_LINE_NO', COUNT(*),
       SUM(CASE WHEN ORDER_LINE_NO IS NULL THEN 0 ELSE 1 END)
FROM dbo.CUST_ORDER_ALLOC

UNION ALL

SELECT 'CUST_ORDER_ALLOC', 'BASE_ID', COUNT(*),
       SUM(CASE WHEN BASE_ID IS NULL OR LTRIM(RTRIM(BASE_ID)) = '' THEN 0 ELSE 1 END)
FROM dbo.CUST_ORDER_ALLOC

UNION ALL

SELECT 'CUST_ORDER_ALLOC', 'LOT_ID', COUNT(*),
       SUM(CASE WHEN LOT_ID IS NULL OR LTRIM(RTRIM(LOT_ID)) = '' THEN 0 ELSE 1 END)
FROM dbo.CUST_ORDER_ALLOC

UNION ALL

SELECT 'CUST_ORDER_ALLOC', 'SPLIT_ID', COUNT(*),
       SUM(CASE WHEN SPLIT_ID IS NULL OR LTRIM(RTRIM(SPLIT_ID)) = '' THEN 0 ELSE 1 END)
FROM dbo.CUST_ORDER_ALLOC

UNION ALL

SELECT 'WORK_ORDER', 'WBS_CUST_ORDER_ID', COUNT(*),
       SUM(CASE WHEN WBS_CUST_ORDER_ID IS NULL OR LTRIM(RTRIM(WBS_CUST_ORDER_ID)) = '' THEN 0 ELSE 1 END)
FROM dbo.WORK_ORDER

UNION ALL

SELECT 'CO_PRODUCT', 'WORKORDER_TYPE', COUNT(*),
       SUM(CASE WHEN WORKORDER_TYPE IS NULL OR LTRIM(RTRIM(CAST(WORKORDER_TYPE AS NVARCHAR(100)))) = '' THEN 0 ELSE 1 END)
FROM dbo.CO_PRODUCT

ORDER BY TABLE_NAME, COLUMN_NAME;