USE `mtm_waitlist`;
DROP INDEX IF EXISTS `idx_WaitlistEntries_Status` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_Status` ON `WaitlistEntries` (`Status`);
DROP INDEX IF EXISTS `idx_WaitlistEntries_Priority_Status` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_Priority_Status` ON `WaitlistEntries` (`Priority`, `Status`);
DROP INDEX IF EXISTS `idx_WaitlistEntries_RequestType` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_RequestType` ON `WaitlistEntries` (`RequestType`);
DROP INDEX IF EXISTS `idx_WaitlistEntries_WorkcenterName` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_WorkcenterName` ON `WaitlistEntries` (`WorkcenterName`);
DROP INDEX IF EXISTS `idx_WaitlistEntries_RequestedAt` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_RequestedAt` ON `WaitlistEntries` (`RequestedAt`);
DROP INDEX IF EXISTS `idx_WaitlistEntries_AssignedToUserId` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_AssignedToUserId` ON `WaitlistEntries` (`AssignedToUserId`);
DROP INDEX IF EXISTS `idx_WaitlistEntries_CreatedByUserId` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_CreatedByUserId` ON `WaitlistEntries` (`CreatedByUserId`);
DROP INDEX IF EXISTS `idx_WaitlistEntries_UpdatedByUserId` ON `WaitlistEntries`;
CREATE INDEX `idx_WaitlistEntries_UpdatedByUserId` ON `WaitlistEntries` (`UpdatedByUserId`);
